Revert "Support namespaces by update mapping tables."
This reverts commit 8a5ee5d2256b365a1fcb07399e5af6d3421b9f74.

Error:

19:22:05  hw/vssim/simulator/vssim_config_manager.c: In function 'set_device_object':
19:22:05  hw/vssim/simulator/vssim_config_manager.c:294:22: error: 'SECTOR_NB' undeclared (first use in this function)
19:22:05    device->sector_nb = SECTOR_NB;
19:22:05                        ^
19:22:05  hw/vssim/simulator/vssim_config_manager.c:294:22: note: each undeclared identifier is reported only once for each function it appears in
19:22:05  hw/vssim/simulator/vssim_config_manager.c: In function 'clear_globals':
19:22:05  hw/vssim/simulator/vssim_config_manager.c:350:5: error: 'SECTOR_NB' undeclared (first use in this function)
19:22:05       SECTOR_NB = 0;
19:22:05       ^

Depends-On: https://review.gerrithub.io/c/davidsaOpenu/qemu/+/1220521