Fix lookup for 32-bit versions of libjson while on 64-bit hosts
Error message:
  ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
         You probably need to set PKG_CONFIG_LIBDIR
         to point to the right pkg-config files for your
         build target.

Fix:
  Install libjson-c-dev package.

Additional changes some of them reqiured to pass tests after the change:
  - no need to pin gcc 4.6
  - small optimization in Dockerfile: Remove kernel scripts before coping entrypoint.sh
    to scripts (saves time when one changes entrypoint.sh)
  - s/compile-nvme-tools.sh/compile-guest-tests.sh
  - s/compile-tests.sh/compile-host-tests.sh
  - installing binutils-2.26 to get rid of unrecognized relocation 0x2a in section text
  - updating PATH in .bashrc for binutils-2.26 to get for interactive bash invocations
  - using --login option for non-interactive bash invocation

Notes:
   Tried to use docker image 18.04. Leaved commented out several additional
   packages to be installed for 18.04. 3.2.16 kernel failed to compile with
   gcc7. Opting to leave 14.04 for now and upgrade to latest stable kernel
   version along with latest docker image

Change-Id: I74edcf061e1c189330c0516382fd1184facbf1bc